#!/usr/bin/env bash
while [ -n  "$1" ]
do
case "$1" in
-a) echo ETO BUKVA AAAAA ;;
-b) param="$2" ;;
*) echo "$1 что это ?" ;;
--) shift
    break
esac
shift
done
for param in "$@"
do
echo $param

done
