
server {
    listen 443 ssl;
    server_name it.loesk.internal;
    client_max_body_size 0;
    ssl_certificate /etc/nginx/certs/loesk.crt;
    ssl_certificate_key /etc/nginx/certs/loesk.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    
    
    location  /git/ {
        proxy_pass http://gitea:3000/;
        include /etc/nginx/proxy.params;
   }

    location / {
        return 301 /git/;
   }
    location /hehe/ {
        root /usr/share/nginx/html;
        index index.html;
    }
}

server {
	listen 80;
	server_name it.loesk.internal;
	return 301 https://$host$request_uri;
}

