upstream frontend {
	server service1:5000;
	server service2:5000;
}

server { 
	listen 80;
	server_name localhost;
	
	location / {
		root /usr/share/nginx/html;
		index index.html;
		try_files $uri $uri/ /index.html;
	}
	
	location /alpha/ {
		proxy_pass http://frontend/;
		include /etc/nginx/proxy.params;
	}
	location /beta/ {
		proxy_pass http://service3:5003/;
		include /etc/nginx/proxy.params;
	}



}

