#!/usr/bin/env bash
read -p "name file -" file
if [ ! -f "$file" ]
then
mypwd=$(pwd)
echo "#!/usr/bin/env bash" >>"$mypwd"/"$file"
chmod +x "$file"
echo "$file" создан и исполняемый!
else
echo файл уже создан
fi




