[webservers]
testserver ansible_host=192.168.122.111
#host_key_checking = False
testserver ansible_host=192.168.122.59

[webservers:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=.vagrant/machines/default/libvirt/private_key










